using DevOps.Primitives.TypeScript;
using System.Collections.Generic;
using static DevOps.Primitives.SourceGraph.Helpers.TypeScript.Common.Files.ModuleTsConfigConstants;

namespace DevOps.Primitives.SourceGraph.Helpers.TypeScript.Common.Files
{
    public static class TsConfigJson
    {
        private const string FileName = "tsconfig.json";

        public static RepositoryFile TsConfig(
            in TsConfigTarget target,
            in TsConfigModule module,
            in IEnumerable<TsConfigLib> lib = default,
            in bool allowJs = default,
            in bool checkJs = default,
            in TsConfigJsx? jsx = default,
            in bool declaration = default,
            in bool sourceMap = default,
            in string outFile = default,
            in string outDir = default,
            in string rootDir = default,
            in bool removeComments = default,
            in bool noEmit = default,
            in bool importHelpers = default,
            in bool downLevelIteration = default,
            in bool isolatedModules = default,
            in bool strict = default,
            in bool noImplicitAny = default,
            in bool strictNullChecks = default,
            in bool strictFunctionsTypes = default,
            in bool strictPropertyInitialization = default,
            in bool noImplicitThis = default,
            in bool alwaysStrict = default,
            in bool noUnusedLocals = default,
            in bool noUnusedParameters = default,
            in bool noImplicitReturns = default,
            in bool noFallthroughCasesInSwitch = default,
            in TsConfigModuleResolution? moduleResolution = default,
            in string baseUrl = default,
            in IDictionary<string, IEnumerable<string>> paths = default,
            in IEnumerable<string> rootDirs = default,
            in IEnumerable<string> typeRoots = default,
            in IEnumerable<string> types = default,
            in bool allowSyntheticDefaultImports = default,
            in bool esModuleInterop = default,
            in bool preserveSymlinks = default,
            in string sourceRoot = default,
            in string mapRoot = default,
            in bool inlineSourceMap = default,
            in bool inlineSources = default,
            in bool experimentalDecorators = default,
            in bool emitDecoratorMetadata = default,
            in IEnumerable<string> includePaths = default,
            params string[] pathParts)
            => new RepositoryFile(
                FileName,
                new TsConfigInfo(
                    target,
                    module,
                    lib,
                    allowJs,
                    checkJs,
                    jsx,
                    declaration,
                    sourceMap,
                    outFile,
                    outDir,
                    rootDir,
                    removeComments,
                    noEmit,
                    importHelpers,
                    downLevelIteration,
                    isolatedModules,
                    strict,
                    noImplicitAny,
                    strictNullChecks,
                    strictFunctionsTypes,
                    strictPropertyInitialization,
                    noImplicitThis,
                    alwaysStrict,
                    noUnusedLocals,
                    noUnusedParameters,
                    noImplicitReturns,
                    noFallthroughCasesInSwitch,
                    moduleResolution,
                    baseUrl,
                    paths,
                    rootDirs,
                    typeRoots,
                    types,
                    allowSyntheticDefaultImports,
                    esModuleInterop,
                    preserveSymlinks,
                    sourceRoot,
                    mapRoot,
                    inlineSourceMap,
                    inlineSources,
                    experimentalDecorators,
                    emitDecoratorMetadata,
                    includePaths
                    ).ToString(),
                pathParts);

        public static RepositoryFile ModuleTsConfig(params string[] pathParts)
            => TsConfig(
                TsConfigTarget.ES5,
                TsConfigModule.commonjs,
                outDir: OutDir,
                sourceMap: true,
                strict: true,
                includePaths: IncludePaths,
                pathParts: pathParts);
    }
}
